version: '3'

services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
      - ./database/data:/var/lib/mysql

  migration:
    container_name: migration
    build:
      context: ./migration
    volumes:
      - ./migration/migrations:/migrations
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend/src:/src
    command: ${MODE}
    ports:
      - 3000:3000
    env_file: .env
volumes:
  db_data:
